image: node:18

stages:
  - install
  - test
  - deploy

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s
  SNYK_TOKEN: $SNYK_TOKEN

cache:
  - key:     
      files:          
      - package-lock.json    
    paths:      
      - node_modules/

install-dependencies:
  stage: install
  script:
    - npm install

contentful:
  stage: install
  script:
    - npm install -g contentful-cli

snyk:
  stage: install
  script:
    - npm install -g snyk

prettier:
  stage: test
  script:
    - npm run format

lint:
  stage: test
  script:
    - npm run lint

jest:
  stage: test
  script:
    - npm ci
    - npm install --global jest
    - npm run test
  coverage: '/All files[^|]|[^|]\s+([\d.]+)/'
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/

security-scan:
  stage: test
  script:
    - npm install -g snyk
    - snyk auth $SNYK_TOKEN || { echo "Failed to authenticate"; exit 1; }
    - snyk test --json > snyk_report.json || { echo "Snyk test failed"; exit 1; }
  artifacts:
    paths:
      - snyk_report.json

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod