image: node:18

stages:
  - install
  - test
  - deploy

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s

cache:
  - key:     
      files:          
      - package-lock.json    
    paths:      
      - node_modules/

install-dependencies:
  stage: install
  script:
    - npm install

contentful:
  stage: install
  script:
    - npm install -g contentful-cli

prettier:
  stage: test
  script:
    - npm run format

lint:
  stage: test
  script:
    - npm run lint

jest:
  stage: test
  script:
    - npm ci
    - npm install --global jest
    - npm run test
  coverage: '/All files[^|]|[^|]\s+([\d.]+)/'
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

lighthouse-tests:
  stage: test
  image: treeder/lighthouse-ci
  script:
    - lighthouse https://tdw-mp1-gabriel-ribeira.tdw-mctw.dev --output json --output-path lighthouse-report.json
  artifacts:
    paths:
      - lighthouse-report.json