image: node:lts

stages:
  - install
  - test
  - deploy

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules/

install-dependencies:
  stage: install
  script:
    - npm install
    - npm install --global jest 

contentful:
  stage: install
  script:
    - npm install -g contentful-cli

prettier:
  stage: test
  script:
    - npm run format

lint:
  stage: test
  script:
    - npm run lint

jest:
  stage: test
  script:
    - npm run test
  coverage: '/All files[^|]|[^|]\s+([\d.]+)/'
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod