name: Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [contentful.deploy]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Create Env'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18.18.1
            
      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
        if: success()

      - name: Install Dependencies
        run: npm ci

      - name: Install Contentful CLI
        run: npm install -g contentful-cli

      - name: Test  
        run: npm run test
        if: success()

      - name: Run Prettier
        run: npm run format
        if: success()

      - name: Run ESLint
        run: npm run lint
        if: success()

      - name: Build
        run: npm run build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        if: success()

      - name: Deploy
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
