name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v18.18.1
          
      - name: Get node version
        id: node
        run: |
           echo "version=$(node -v)" >>$GITHUB_OUTPUT
  
        if: success()
            
      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
        if: success()

      - name: Install Dependencies
        run: npm ci

      - name: Install Contentful CLI
        run: npm install -g contentful-cli

      - name: Run Prettier
        run: npm run format
        if: success()

      - name: Run ESLint
        run: npm run lint
        if: success()

      - name: Build
        run: npm run build
        if: success()

      - name: Deploy
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
