name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        if: success()

      - name: Run Prettier
        run: npm run format
        if: success()

      - name: Run ESLint
        run: npm run lint
        if: success()

      - name: Build
        run: npm run build
        if: success()

      - name: Deploy
        run: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
