name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        if: success()

      - name: Run Prettier
        run: npm run format
        if: success()

      - name: Run ESLint
        run: npm run lint
        if: success()


      - name: Export Contentful Data
        run: contentful space export --space-id ${{ secrets.CONTENTFUL_SPACE_ID }} --management-token ${{ secrets.CONTENTFUL_TOKEN }} --export-dir contentful-backup

      - name: Build
        run: npm run build
        if: success()

      - name: Deploy
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
