name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci
        if: success()

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint
