name: Contentful

on:
  repository_dispatch:
        types: [contentful.deploy]

jobs: 
    contentful:
        runs-on: ubuntu-latest
        steps:
          - name: Contenful Message
            run: echo "Conteúdo atualizado"